<?php
/**
 * Export SEO Audit Report as CSV
 * Downloads a CSV file with all issues, action items, and status.
 *
 * GET ?audit_id=15
 */

require_once __DIR__ . '/../../includes/helpers.php';
require_once __DIR__ . '/../../includes/auth.php';

auth_start();

if (!auth_check()) {
    http_response_code(401);
    echo 'Unauthorized';
    exit;
}

$db = require __DIR__ . '/../../includes/db.php';
$user_id = auth_user_id();

$audit_id = (int)($_GET['audit_id'] ?? 0);

if (!$audit_id) {
    http_response_code(400);
    echo 'audit_id required';
    exit;
}

// Verify ownership
$stmt = $db->prepare('SELECT a.*, s.domain, s.name as site_name FROM seo_audits a JOIN sites s ON a.site_id = s.id WHERE a.id = ? AND s.user_id = ?');
$stmt->execute([$audit_id, $user_id]);
$audit = $stmt->fetch();

if (!$audit) {
    http_response_code(404);
    echo 'Audit not found';
    exit;
}

// Get only open/actionable issues (exclude auto-fixed)
$stmt = $db->prepare('SELECT * FROM seo_issues WHERE audit_id = ? AND status NOT IN ("resolved", "ignored", "fixed_by_snippet", "fix_applied") ORDER BY FIELD(severity, "critical", "warning", "info"), type, url');
$stmt->execute([$audit_id]);
$issues = $stmt->fetchAll();

// Use AI to generate specific suggestions for each issue
require_once __DIR__ . '/../../includes/haiku.php';

$ai_suggestions = [];
if (!empty($issues)) {
    try {
        $issues_text = '';
        foreach ($issues as $idx => $issue) {
            $issues_text .= ($idx + 1) . ". [{$issue['type']}] URL: {$issue['url']} — {$issue['description']}\n";
        }

        $system = "You are an SEO expert. Generate specific, ready-to-use fix text for each issue. "
            . "For missing meta descriptions: write the actual meta description text (120-160 chars). "
            . "For long titles: write a shorter version (under 60 chars). "
            . "For missing alt text: suggest descriptive alt text based on the image filename. "
            . "For other issues: give a specific, actionable one-line fix. "
            . "Reply with ONLY a JSON array of strings, one suggestion per issue, in the same order. No markdown, no explanation.";

        $user_msg = "Website: {$audit['domain']} ({$audit['site_name']})\n\nIssues:\n{$issues_text}";

        $ai_result = haiku_chat($system, $user_msg, 4096);
        if ($ai_result['success'] && !empty($ai_result['content'])) {
            if (preg_match('/\[.*\]/s', $ai_result['content'], $matches)) {
                $ai_suggestions = json_decode($matches[0], true) ?: [];
            }
        }
    } catch (\Exception $e) {
        // AI suggestions are optional — continue without them
    }
}

// Generate CSV
$filename = 'seo-audit-' . $audit['domain'] . '-' . date('Y-m-d', strtotime($audit['run_at'])) . '.csv';

header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $filename . '"');

$output = fopen('php://output', 'w');

// Add BOM for Excel UTF-8 compatibility
fprintf($output, chr(0xEF) . chr(0xBB) . chr(0xBF));

// Header row
fputcsv($output, [
    'SEO Audit Report: ' . $audit['site_name'] . ' (' . $audit['domain'] . ')',
]);
fputcsv($output, [
    'Date: ' . date('d M Y, h:i A', strtotime($audit['run_at'])),
    'Score: ' . $audit['score'] . '/100',
    'Pages Crawled: ' . $audit['pages_crawled'],
]);
fputcsv($output, []); // blank row

// Column headers
fputcsv($output, [
    '#',
    'Priority',
    'Type',
    'Page URL',
    'Issue',
    'Suggested Fix',
    'Recommended Text / Action',
]);

$i = 1;
foreach ($issues as $idx => $issue) {
    $priority = $issue['severity'] === 'critical' ? 'HIGH' : ($issue['severity'] === 'warning' ? 'MEDIUM' : 'LOW');

    $ai_text = $ai_suggestions[$idx] ?? '';

    fputcsv($output, [
        $i++,
        $priority,
        str_replace('_', ' ', ucfirst($issue['type'])),
        $issue['url'],
        $issue['description'],
        $issue['suggested_fix'] ?? '',
        $ai_text,
    ]);
}

// Summary at bottom
fputcsv($output, []);
fputcsv($output, ['SUMMARY']);
fputcsv($output, ['SEO Score', $audit['score'] . '/100']);
fputcsv($output, ['Action Items', count($issues)]);
fputcsv($output, ['Critical (HIGH)', count(array_filter($issues, fn($i) => $i['severity'] === 'critical'))]);
fputcsv($output, ['Warnings (MEDIUM)', count(array_filter($issues, fn($i) => $i['severity'] === 'warning'))]);
fputcsv($output, ['Info (LOW)', count(array_filter($issues, fn($i) => $i['severity'] === 'info'))]);
fputcsv($output, []);
fputcsv($output, ['Note: Issues already auto-fixed by ContentAgent are not included in this report.']);
fputcsv($output, ['Recommended text in column G is AI-generated — please review before applying.']);
fputcsv($output, []);
fputcsv($output, ['Report generated by ContentAgent — contentagent.xceedtech.in']);

fclose($output);
