<?php
/**
 * 404 / Not-Found page generator — produces an on-brand 404 template
 * per customer platform. Catches the URLs that didn't make it into the
 * redirect map (mistypes, bots, long-tail).
 *
 * Inputs (read from sites + current_site_urls):
 *   - site name + domain
 *   - brand primary colour (sites.brand_colors JSON: { primary })
 *   - 6 popular live URLs across types (home + collection + product + blog + page + contact)
 *
 * Outputs per platform (raw text, ready to paste):
 *   - Next.js App Router: not-found.tsx
 *   - Shopify: snippets/404-suggestions.liquid + sections/404-content.liquid
 *
 * No Claude call at this stage — a clean template + brand context is enough.
 * If the user wants more personality later we can layer Claude-generated copy.
 */

require_once __DIR__ . '/helpers.php';

/**
 * Pick a curated set of "helpful destinations" from the live URL inventory.
 * Returns array of [path => label] in a reasonable display order.
 */
function nfg_pick_destinations(PDO $db, int $site_id): array
{
    $stmt = $db->prepare("SELECT path, url_type, title FROM current_site_urls WHERE site_id = ? ORDER BY id");
    $stmt->execute([$site_id]);
    $by_type = ['home' => [], 'collection' => [], 'product' => [], 'page' => [], 'blog' => [], 'other' => []];
    foreach ($stmt->fetchAll() as $r) {
        $t = $r['url_type'] ?: 'other';
        if (!isset($by_type[$t])) $by_type[$t] = [];
        $by_type[$t][] = ['path' => $r['path'], 'title' => $r['title'] ?: null];
    }

    // Preferred destinations:
    //   1. Home (/) — always
    //   2. Contact (if exists as a page)
    //   3. Top collection
    //   4. Top product / blog landing
    //   5. About (if exists)
    //   6. Filler from biggest type
    $picks = [];
    $seen  = [];
    $add = function (string $path, string $label) use (&$picks, &$seen) {
        $path = $path === '' ? '/' : $path;
        if (isset($seen[$path])) return;
        $picks[$path] = $label;
        $seen[$path] = true;
    };

    $add('/', 'Home');

    $candidates = [
        '/contact' => 'Contact us',
        '/about'   => 'About',
        '/pages/contact' => 'Contact us',
        '/pages/about'   => 'About',
    ];
    foreach ($candidates as $p => $label) {
        foreach (array_merge($by_type['page'], $by_type['other']) as $row) {
            if ($row['path'] === $p) $add($p, $label);
        }
    }

    foreach (array_slice($by_type['collection'], 0, 2) as $row) {
        $label = $row['title'] ?: nfg_slug_to_title(basename($row['path']));
        $add($row['path'], $label);
    }
    foreach (array_slice($by_type['blog'], 0, 1) as $row) {
        $add($row['path'], $row['title'] ?: 'Latest writing');
    }
    foreach (array_slice($by_type['page'], 0, 2) as $row) {
        if (count($picks) >= 6) break;
        $label = $row['title'] ?: nfg_slug_to_title(basename($row['path']));
        $add($row['path'], $label);
    }
    foreach (array_slice($by_type['product'], 0, 2) as $row) {
        if (count($picks) >= 6) break;
        $label = $row['title'] ?: nfg_slug_to_title(basename($row['path']));
        $add($row['path'], $label);
    }
    foreach (array_slice($by_type['other'], 0, 4) as $row) {
        if (count($picks) >= 6) break;
        $label = $row['title'] ?: nfg_slug_to_title(basename($row['path']));
        $add($row['path'], $label);
    }

    return $picks;
}

function nfg_slug_to_title(string $slug): string
{
    $slug = preg_replace('/\.(html?|php|aspx?)$/', '', $slug);
    $slug = str_replace(['-', '_'], ' ', $slug);
    return ucwords($slug) ?: 'View page';
}

function nfg_primary_colour(array $site): string
{
    $colors = json_decode($site['brand_colors'] ?? '{}', true) ?: [];
    $hex = $colors['primary'] ?? $colors['accent'] ?? '#0f172a';
    if (!preg_match('/^#?[0-9a-f]{3,8}$/i', $hex)) $hex = '#0f172a';
    if ($hex[0] !== '#') $hex = '#' . $hex;
    return $hex;
}

/**
 * Generate a Next.js App Router not-found.tsx file. Self-contained (no
 * external CSS), uses inline styles so the customer doesn't have to wire up
 * Tailwind or another design system to use it.
 */
function nfg_generate_nextjs(array $site, array $destinations): string
{
    $name    = trim((string)$site['name']);
    $domain  = trim((string)$site['domain']);
    $primary = nfg_primary_colour($site);

    $links = '';
    foreach ($destinations as $path => $label) {
        $p = addslashes($path);
        $l = htmlspecialchars($label, ENT_QUOTES, 'UTF-8');
        $links .= "          <Link href=\"{$p}\" style={linkStyle}>{`{$l}`}</Link>\n";
    }

    return <<<TSX
// Generated by ContentAgent for {$name} ({$domain}).
// App-router 404 page. Place this at app/not-found.tsx in your Next.js project.
// Visitors who hit any URL not matched by a route or by your redirect map will
// see this page instead of the default Next.js 404. Inline styles only — no
// dependency on Tailwind / a design system.

import Link from 'next/link';

const containerStyle: React.CSSProperties = {
  maxWidth: '720px',
  margin: '0 auto',
  padding: '80px 24px',
  fontFamily: 'system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
  color: '#0f172a',
};
const eyebrowStyle: React.CSSProperties = {
  fontSize: '12px',
  textTransform: 'uppercase',
  letterSpacing: '0.6px',
  color: '{$primary}',
  marginBottom: '8px',
  fontWeight: 600,
};
const headlineStyle: React.CSSProperties = {
  fontSize: '36px',
  lineHeight: 1.1,
  margin: '0 0 16px',
  fontWeight: 700,
};
const subStyle: React.CSSProperties = {
  fontSize: '15px',
  color: '#475569',
  lineHeight: 1.6,
  margin: '0 0 32px',
  maxWidth: '520px',
};
const linksWrapStyle: React.CSSProperties = {
  display: 'grid',
  gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))',
  gap: '10px',
  marginBottom: '32px',
};
const linkStyle: React.CSSProperties = {
  display: 'block',
  padding: '12px 14px',
  border: '1px solid #e2e8f0',
  borderRadius: '8px',
  color: '#0f172a',
  textDecoration: 'none',
  fontSize: '14px',
  fontWeight: 500,
  transition: 'all 0.15s',
  background: '#fff',
};
const footStyle: React.CSSProperties = {
  fontSize: '13px',
  color: '#64748b',
  borderTop: '1px solid #e2e8f0',
  paddingTop: '16px',
};

export default function NotFound() {
  return (
    <main style={containerStyle}>
      <div style={eyebrowStyle}>404 — page not found</div>
      <h1 style={headlineStyle}>We couldn’t find that page.</h1>
      <p style={subStyle}>
        The link you followed may be outdated, or the page might have been moved.
        Here are some places that might help you get to what you were looking for:
      </p>
      <div style={linksWrapStyle}>
{$links}      </div>
      <div style={footStyle}>
        Still stuck? <a href="/contact" style={{ color: '{$primary}', fontWeight: 500 }}>Get in touch with the {$name} team</a> and we’ll help.
      </div>
    </main>
  );
}

TSX;
}

/**
 * Generate a Shopify 404 section/snippet. Shopify themes already serve a
 * /404 route — what the customer needs is the SECTION/SNIPPET to drop in.
 */
function nfg_generate_shopify(array $site, array $destinations): string
{
    $name    = trim((string)$site['name']);
    $primary = nfg_primary_colour($site);

    $links = '';
    foreach ($destinations as $path => $label) {
        $p = htmlspecialchars($path, ENT_QUOTES, 'UTF-8');
        $l = htmlspecialchars($label, ENT_QUOTES, 'UTF-8');
        $links .= "      <a href=\"{$p}\" class=\"ca404-link\">{$l}</a>\n";
    }

    return <<<LIQUID
{% comment %}
Generated by ContentAgent for {$name}.
Drop this into sections/ca-404.liquid. Then edit templates/404.liquid (or
404.json on Online Store 2.0 themes) to render this section: include 'ca-404'
or add { "type": "ca-404" } to the section list.

Visitors who hit any URL not matched by Shopify routes or your URL Redirects
will see this page. Inline styles — no theme CSS dependency.
{% endcomment %}

<div class="ca404">
  <p class="ca404-eyebrow">404 — page not found</p>
  <h1 class="ca404-headline">We couldn&rsquo;t find that page.</h1>
  <p class="ca404-sub">The link you followed may be outdated, or the page might have moved. Here are some places that might help you get to what you were looking for:</p>
  <div class="ca404-links">
{$links}  </div>
  <p class="ca404-foot">Still stuck? <a href="/pages/contact">Get in touch with the {$name} team</a> and we&rsquo;ll help.</p>
</div>

<style>
.ca404 { max-width: 720px; margin: 0 auto; padding: 80px 24px; font-family: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; color: #0f172a; }
.ca404-eyebrow { font-size: 12px; text-transform: uppercase; letter-spacing: 0.6px; color: {$primary}; margin-bottom: 8px; font-weight: 600; }
.ca404-headline { font-size: 36px; line-height: 1.1; margin: 0 0 16px; font-weight: 700; }
.ca404-sub { font-size: 15px; color: #475569; line-height: 1.6; margin: 0 0 32px; max-width: 520px; }
.ca404-links { display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 10px; margin-bottom: 32px; }
.ca404-link { display: block; padding: 12px 14px; border: 1px solid #e2e8f0; border-radius: 8px; color: #0f172a; text-decoration: none; font-size: 14px; font-weight: 500; background: #fff; }
.ca404-link:hover { border-color: {$primary}; }
.ca404-foot { font-size: 13px; color: #64748b; border-top: 1px solid #e2e8f0; padding-top: 16px; }
.ca404-foot a { color: {$primary}; font-weight: 500; }
</style>

LIQUID;
}
