<?php
/**
 * Per-platform redirect exporters. Each function takes the same input —
 * an array of [['from_path' => str, 'to_path' => str], ...] — and returns
 * a string ready to paste into that platform's deploy mechanism.
 *
 * Platform identity comes from sites.platform; the redirects.php UI reads
 * it and surfaces the appropriate download button + walkthrough.
 *
 * Tiered support:
 *   First-class: nextjs, shopify, wordpress, apache, nginx, netlify, vercel
 *   Universal fallback: CSV  (works for Webflow/Wix/Squarespace manual entry,
 *                             custom stacks, unknown platforms)
 */

require_once __DIR__ . '/helpers.php';

/** Apache .htaccess Redirect rules. Plain text. */
function redirect_export_apache_htaccess(array $redirects): string
{
    $lines = [];
    $lines[] = "# Generated by ContentAgent. 301 redirects.";
    $lines[] = "# Paste these into your site's .htaccess file at the root of your web directory.";
    $lines[] = "# If you don't have an .htaccess file yet, create one. If you do, append these lines.";
    $lines[] = "";
    $lines[] = "<IfModule mod_rewrite.c>";
    $lines[] = "  RewriteEngine On";
    foreach ($redirects as $r) {
        $from = $r['from_path']; $to = $r['to_path'];
        if ($from === '' || $to === '') continue;
        // Use Redirect 301 instead of RewriteRule because it's simpler and
        // doesn't require escaping. Works for path-only matches.
        $lines[] = "  Redirect 301 " . $from . " " . $to;
    }
    $lines[] = "</IfModule>";
    $lines[] = "";
    $lines[] = "# Optional: serve a custom 404 page (see ContentAgent 404 download).";
    $lines[] = "# ErrorDocument 404 /404.html";
    return implode("\n", $lines) . "\n";
}

/** nginx location blocks. Paste into your server block. */
function redirect_export_nginx(array $redirects): string
{
    $lines = [];
    $lines[] = "# Generated by ContentAgent. 301 redirects.";
    $lines[] = "# Paste these inside your server { ... } block in nginx.conf";
    $lines[] = "# or your site's per-domain config (typically /etc/nginx/sites-available/<your-site>).";
    $lines[] = "# After saving: sudo nginx -t  (test) then sudo systemctl reload nginx.";
    $lines[] = "";
    foreach ($redirects as $r) {
        $from = $r['from_path']; $to = $r['to_path'];
        if ($from === '' || $to === '') continue;
        // Exact-match location with permanent redirect
        $lines[] = "location = " . $from . " { return 301 " . $to . "; }";
    }
    $lines[] = "";
    $lines[] = "# Optional: serve a custom 404 page (see ContentAgent 404 download).";
    $lines[] = "# error_page 404 /404.html;";
    return implode("\n", $lines) . "\n";
}

/** Netlify / Cloudflare Pages _redirects file. Same format on both. */
function redirect_export_netlify(array $redirects): string
{
    $lines = [];
    $lines[] = "# Generated by ContentAgent. 301 redirects.";
    $lines[] = "# Save this file as `_redirects` at the root of your project (next to index.html or your build output).";
    $lines[] = "# Works on Netlify AND Cloudflare Pages — both read the same file format.";
    $lines[] = "";
    foreach ($redirects as $r) {
        $from = $r['from_path']; $to = $r['to_path'];
        if ($from === '' || $to === '') continue;
        $lines[] = sprintf("%-60s %-60s 301", $from, $to);
    }
    return implode("\n", $lines) . "\n";
}

/** Vercel vercel.json redirects block. Drop in repo root. */
function redirect_export_vercel_json(array $redirects): string
{
    $entries = [];
    foreach ($redirects as $r) {
        $from = $r['from_path']; $to = $r['to_path'];
        if ($from === '' || $to === '') continue;
        $entries[] = [
            'source'      => $from,
            'destination' => $to,
            'permanent'   => true,
        ];
    }
    $payload = [
        '_comment'  => 'Generated by ContentAgent. If you have an existing vercel.json, merge the redirects array into yours.',
        'redirects' => $entries,
    ];
    return json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n";
}

/**
 * WordPress — three options because WP customers have different comfort levels.
 * The exporter returns a single text file containing ALL three so the user picks.
 */
function redirect_export_wordpress(array $redirects): string
{
    $lines = [];
    $lines[] = "# Generated by ContentAgent. 301 redirects for WordPress.";
    $lines[] = "# THREE OPTIONS — pick the one that fits your skill level + plugin policy.";
    $lines[] = "# =============================================================================";
    $lines[] = "";
    $lines[] = "# OPTION 1 — Redirection plugin (easiest, recommended)";
    $lines[] = "# 1. Install the free \"Redirection\" plugin (by John Godley) from the WP plugin directory.";
    $lines[] = "# 2. Go to Tools → Redirection → Import/Export tab.";
    $lines[] = "# 3. Upload the CSV file we generated alongside this one (ca-redirects.csv).";
    $lines[] = "# 4. Done — redirects are active immediately.";
    $lines[] = "";
    $lines[] = "# OPTION 2 — .htaccess (no plugin)";
    $lines[] = "# Paste the block below into your WP root .htaccess file ABOVE the # BEGIN WordPress line.";
    $lines[] = "";
    $lines[] = "<IfModule mod_rewrite.c>";
    $lines[] = "  RewriteEngine On";
    foreach ($redirects as $r) {
        if ($r['from_path'] === '' || $r['to_path'] === '') continue;
        $lines[] = "  Redirect 301 " . $r['from_path'] . " " . $r['to_path'];
    }
    $lines[] = "</IfModule>";
    $lines[] = "";
    $lines[] = "# OPTION 3 — theme functions.php (PHP-savvy)";
    $lines[] = "# Paste this whole function into your active theme's functions.php (preferably a child theme).";
    $lines[] = "";
    $lines[] = "function ca_redirects() {";
    $lines[] = "    \$map = [";
    foreach ($redirects as $r) {
        if ($r['from_path'] === '' || $r['to_path'] === '') continue;
        $from = addslashes($r['from_path']); $to = addslashes($r['to_path']);
        $lines[] = "        '{$from}' => '{$to}',";
    }
    $lines[] = "    ];";
    $lines[] = "    \$req = parse_url(\$_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH);";
    $lines[] = "    if (isset(\$map[\$req])) {";
    $lines[] = "        wp_redirect(\$map[\$req], 301);";
    $lines[] = "        exit;";
    $lines[] = "    }";
    $lines[] = "}";
    $lines[] = "add_action('template_redirect', 'ca_redirects');";
    return implode("\n", $lines) . "\n";
}

/**
 * Universal fallback — plain CSV. Works for:
 *   - Webflow's bulk redirect importer
 *   - Wix's URL Redirect Manager (manual entry, but the data is here in clean form)
 *   - Squarespace's URL Mappings (manual)
 *   - Any platform with a CSV upload feature
 *   - Hand-off to a developer on any stack
 */
function redirect_export_generic_csv(array $redirects): string
{
    $out = fopen('php://temp', 'w+');
    fputcsv($out, ['from_path', 'to_path', 'redirect_type']);
    foreach ($redirects as $r) {
        if ($r['from_path'] === '' || $r['to_path'] === '') continue;
        fputcsv($out, [$r['from_path'], $r['to_path'], '301']);
    }
    rewind($out);
    $body = stream_get_contents($out);
    fclose($out);
    return $body;
}

/** Returns the supported platforms + their metadata for UI rendering. */
function redirect_platform_choices(): array
{
    return [
        'nextjs'    => ['label' => 'Next.js',                     'filename' => 'next.config.js',   'action' => 'export_next_config'],
        'shopify'   => ['label' => 'Shopify',                     'filename' => null,               'action' => 'apply_to_shopify',  'apply' => true],
        'wordpress' => ['label' => 'WordPress',                   'filename' => 'wp-redirects.txt', 'action' => 'export_wordpress'],
        'apache'    => ['label' => 'Apache / .htaccess',          'filename' => '.htaccess',        'action' => 'export_apache'],
        'nginx'     => ['label' => 'nginx',                       'filename' => 'redirects.conf',   'action' => 'export_nginx'],
        'netlify'   => ['label' => 'Netlify / Cloudflare Pages',  'filename' => '_redirects',       'action' => 'export_netlify'],
        'vercel'    => ['label' => 'Vercel (non-Next.js)',        'filename' => 'vercel.json',      'action' => 'export_vercel'],
        'custom'    => ['label' => 'Other / unknown',             'filename' => 'redirects.csv',    'action' => 'export_csv'],
    ];
}
